#!/bin/sh

# In case we have a slow-to-appear interface (e.g. eth-over-USB),
# and we need to configure it, wait until it appears, but not too
# long either. IF_WAIT_DELAY is in seconds.

if [ "${IF_WAIT_DELAY}" -a ! -e "/sys/class/net/${IFACE}" ]; then
    printf "Waiting for interface %s to appear" "${IFACE}"
    while [ ${IF_WAIT_DELAY} -gt 0 ]; do
        if [ -e "/sys/class/net/${IFACE}" ]; then
            printf "\n"
            exit 0
        fi
        sleep 1
        printf "."
        : $((IF_WAIT_DELAY -= 1))
    done
    printf " timeout!\n"
    exit 1
fi

iface_name=$(realpath "/sys/class/net/${IFACE}")
if [ -e "${iface_name}" ]; then
    iface_info=$(echo "${iface_name}" | sed 's|.*platform/\(.*\)/net/.*|\1|')
    if [ "${iface_info}" == "fe1c0000.ethernet" ]; then
        ip link set "${IFACE}" name "wan"
    elif [ "${iface_info}" == "a40c00000.pcie/pci0003:30/0003:30:00.0/0003:31:00.0" ]; then
        ip link set "${IFACE}" name "lan"
    fi
fi

